### ISSUE TITLE
Allow for advancing by one generation

### ISSUE THREAD

**Issue by joelangeway** [raganwald/hashlife#26]
Currently it advances by many generations or iterations or steps or whatever every time I hit the advance button. It would be a lot more fun potentially if I could advance one generation at a time to allow for some experimentation.

**Comment by raganwald** [comment]
It's an interesting problem for HashLife to calculate futures one generation at a time. The base algorithm takes a square with sides 2^n and calculates the future 2^(n-1) generations in the future. So if you have an active area that is 16 by 16, it will jump 8 generations into the future.

The full algorithm does have a recursive way to calculate futures that are smaller than 2^(n-1), but it actually requires _more_ calculations to do it. I'll work on this and undo next.
